/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AudioButton: typeof import('./src/components/audio-button.vue')['default']
    CountToCommon: typeof import('./src/components/count-to-common.vue')['default']
    EchartsCommon: typeof import('./src/components/echarts-common.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchCommon: typeof import('./src/components/search-common.vue')['default']
    TableCommon: typeof import('./src/components/table-common.vue')['default']
  }
}
